dist: trusty
sudo: false
addons:
  chrome: stable
language: node_js
node_js:
  - "6"
  - "8"
  - "10"
script: "npm run unit"
after_script: "npm install codecov.io && cat ./test/unit/coverage/lcov.info | codecov"
